### PR TITLE
Chaos Fixes

### LINKED ISSUE #1360: Dragon Ogor Shaggoth missing spellnumber
Device: mobile
Army: chaos Beastmen
Unit: Dragon Ogor Shaggoth

The named unit is missing the information about the amount of spells it can cast/unbind

### LINKED ISSUE #1361: Legion of Chaos Ascendant still broken
Someone needs to go over this with a fine-toothed comb or just redo it altogether. There are characters who, when chosen as general, aren't able to take command traits, artifacts, spells, etc. Forge World daemon units still aren't in the list. Except for the Verminlord Corrupter, why are all of the Skaven daemons and endless spells in some wierd category called "Uncategorized"?

### LINKED ISSUE #1363: [Anon] Bug report: Chaos - Skaven.catz
**File:** Chaos - Skaven.catz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** Thanquol on Boneripper is missing the option to select a spell from the Grey Seers' Lore of Ruin. I think the "GREY SEER" keyword should entitle him to one.

### PR DESCRIPTION
**Pull request by cartag**
Daemons to LoCA, Skaven reworked for LoCA, skaven data fix.
Closes #1363 
Closes #1361 
Closes #1360

### CODE REVIEW

**Comment by cartag** [comment]
/release

Chaos Bug Fixes

**Comment by cartag** [comment]
/release

Chaos Bug Fixes

**Comment by cartag** [comment]
/release

Chaos Bug Fixes

**Comment by BriB23** [comment]
Still can't add command traits, artifacts or spells from the Wrath of the Everchosen campaign book to eligible units (generals, heroes, wizards). Missing Forgeworld daemon units such as Daemon Toads of Nurgle, Pox Riders, K'Daai Fireborn. Missing Daemon Princes from the Slaves to Darkness battletome.

**Comment by cartag** [comment]
Again: You need to be specific. Skaven units are able to use take the traits, artefacts, etc. Make sure your data has actually updated. It sometimes takes hours for it to trickles down and do the actual release. 

Daemon Toads of Nurgle, Pox Riders, K'Daai Fireborn are all in there. 
image

The Daemon Prince from the StD battletome is LITERALLY titled Slaves To Darkness Daemon Prince. 
image

**Comment by BriB23** [comment]
Yes, sorry, you're right about the units mentioned. However, unless I'm mistaken, every non-named unit with the **Chaos Daemon** and **Hero** keyword should be able to take an artefact from the Gifts of the Devoted. If he's the general he should be able to take one of the Scions of the Ruinous Powers command traits. And any non-unique unit with the **Wizard** keyword should be able to take spells from the Lore of Ruinous Sorcery.

Personally, I don't know where the official points for the Exalted Greater Daemons are listed but looking at the Warscroll Builder on the Warhammer Community site, all four of them have lower points listed there. I honestly don't know which is correct.

Khorne 540 vs 580
Tzeentch 480 vs 500
Nurgle 400 vs 460
Slaanesh 360 vs 440

**Comment by cartag** [comment]
Yes, I am fully aware which units are eligible for artefacts, traits, and lores. What I am saying is that you've not listed any that are missing said rules. When I asked for specifics, I meant can you please name individual units that do NOT have the options to take those things. As you have so far been unable to do so, I am ignoring any future comments about it until you can name at least one. 

Points for the exalted greater daemons are being updated. The points are listed in the Monstrous Arcanum PDF on ForgeWorld's site.

**Comment by BriB23** [comment]
The Verminlord Corrupter, for one. I’ll let you go through the rest. Most of the non-unique characters have the same problem. HOW HARD IS IT TO EVEN CHECK ONE YOURSELF INSTEAD OF WASTING YOUR TIME REPLYING LIKE THIS?

**Comment by cartag** [comment]
Verminlord Corruptor has all the appropriate choices. Now I would ask you to stop wasting my time, which you seem to be so concerned with, wait for the release that was made an hour ago, see yourself that you are wrong, and stop being an insufferable tool.  

image

**Comment by BriB23** [comment]
That’s not what mine looks like. The Artefacts, Command Traits and Spell Lores are not clickable or interactive at all. So kindly go fuck yourself.

[cid:image003.png@01D64AF1.883CAD60]

**Comment by cartag** [comment]
Which is why I was saying to wait for the update and to update your data. Go fornicate with a land mine.

**Comment by BriB23** [comment]
So I was correct. Yet today is the first time you’ve said that it’s fixed (in a future update). Before you were insistent that I was full of shit and telling me to give an example. I did. You’re very bad at this.

**Comment by cartag** [comment]
For the record, this was fixed yesterday. Not in the release that was pushed an hour ago.

**Pull request merged**
