### PR TITLE
Add Melusai Ironscale.

### LINKED ISSUE #1581: Melusai Ironscale Missing
The Melusai Ironscale is missing from the Daughters of Khaine roster. Unsure if this has been reported previously.

### PR DESCRIPTION
**Pull request by rweyrauch**
Fix #1581

### CODE REVIEW

**Comment by Sushiki** [comment]
This is still an issue. Melusai Ironscale is missing from everything but the battalions. She also has no point value in battalion.

**Comment by rweyrauch** [comment]
I just checked on the latest release 2.2.20 and Melusai Ironscale is working correctly.   What version of the DoK catalog are you using?

**Comment by cartag** [comment]
I think I broke it

**Comment by rweyrauch** [comment]
Seems to work on 2.2.20.

**Comment by cartag** [comment]
That's because the version I broke it with is the same version that you uploaded with the fix. I didn't grab your copy first before putting up my own.

**Comment by cartag** [comment]
I've already fixed it and pushed a release with it fixed.

**Comment by Sushiki** [comment]
how do I get your fix on battlescribe, updating from within the application is doing nothing, melusai ironscale is still not a leader option, nor is there any point value for the one in the battalions. I'm new to coming here so is there somewhere here I can download the updated version?

**Comment by cartag** [comment]
The release should be live within 8 hours, just update your data when it's available and it'll download. If you're comfortable with git you could also download the repo and unzip it in your data file directory to get it before that. 

If you're just dying to make a list in the interim, set your points value to 860 or 1860 instead of 1000 or 2000 points to take the 140 points for Melusai into account.

**Comment by Sushiki** [comment]
thank you so much!

**Comment by Sushiki** [comment]
The point value is fixed but she's not listed in "leaders" section as I said before, so the battalions are fixed but the character is not available outside the battalion. Not sure if there's some special reason to that but seems wrong? or is she uniquely only available in the battalions and not outside it?

**Comment by rweyrauch** [comment]
Just fixed her again. :(

I've attached a catalog with the fix.   Remove the .zip extension before using it.   Github only lets me attach a file with a zip extension.

[Age of Sigmar.bsr.zip](https://github.com/BSData/warhammer-age-of-sigmar/files/5648868/Age.of.Sigmar.bsr.zip)

**Pull request merged**
