### PR TITLE
New Gloomspite Roster

### PR DESCRIPTION
**Pull request by UrsinePatriarch**
Dunno if I'm doing this right, but this is the entire Gloomspite Gitz roster file, so please integrate it into the main repo.

Sorry for anything I'm doing wrong.

### CODE REVIEW

**Comment by rweyrauch** [comment]
You're going to need to upload the text-only version of the GG catalog.   The .catz file is a compressed binary file (a zip file).   You can use the DataEditor and save the GG catalog as a plain old text file using the .cat option.

I did a quick on the new GG catalog and things look really good.   Well done.

**Comment by UrsinePatriarch** [comment]
I'm not sure what I'm supposed to do now; I have the .cat file but this upload system seems relatively convoluted to me.

I opened up another pull request but I'm pretty sure I closed it by accident. 

I'm really sorry but I'd appreciate a step-by-step or a direction to one, in any case.

**Comment by rweyrauch** [comment]
> I'm not sure what I'm supposed to do now; I have the .cat file but this upload system seems relatively convoluted to me.
> 
> I opened up another pull request but I'm pretty sure I closed it by accident.
> 
> I'm really sorry but I'd appreciate a step-by-step or a direction to one, in any case.
> 
> Legit not sure if this works now or not; sorry again for all the trouble.

Looks great.  You are _not_ causing any trouble.   I'll test your changes (points, etc) tomorrow morning.

**Comment by UrsinePatriarch** [comment]
I have absolutely no idea how to delete the one with the wrong naming scheme, so I just uploaded another identical file with the right one; again, apologies in advance.

Thanks for the patience, Rick; I'm trying my best to stumble my way through this place cause I hope to contribute more in the future, so it's nice to be helped so much like this.

**Pull request merged**
