### PR TITLE
Re-enter allegiance and artefacts for DISP, DC and FP.

### PR DESCRIPTION
**Pull request by rweyrauch**

### CODE REVIEW

**Comment by rweyrauch** [comment]
The previous pull-request with the same changes did not actually work.   Re-trying.

**Comment by rweyrauch** [comment]
Wrong button.  Meant to comment only.

**Comment by OftKilted** [comment]
Recommend that any future work is split out into separate cat files for the baseline Allegiances. (If there are Battle Traits/Allegiance Abilities etc. consider putting it in its own cat.)

**Comment by rweyrauch** [comment]
This will be the last change to the monolithic catalog.   The splitting begins now.

**Pull request merged**
